x-common-environment: &lmpenv
  environment:
    - LMPUSER=lmpuser
    - CFGSERVER=ghead

services:
  head:
    image: nerozane/lmpclstr-head:1.1
    hostname: ghead
    container_name: lmphead
    <<: *lmpenv
    networks:
      - guriang
    volumes:
      - slurmstate:/var/slurm
      - gshare:/home/share
      - ./slurm.conf:/usr/local/etc/slurm.conf

  node01:
    image: nerozane/lmpclstr-node:1.1
    hostname: node01
    container_name: lmpnode01
    <<: *lmpenv
    networks:
      - guriang
    volumes:
      - gshare:/home/share
      - ./slurm.conf:/usr/local/etc/slurm.conf

  node02:
    image: nerozane/lmpclstr-node:1.1
    hostname: node02
    container_name: lmpnode02
    <<: *lmpenv
    networks:
      - guriang
    volumes:
      - gshare:/home/share
      - ./slurm.conf:/usr/local/etc/slurm.conf

  node03:
    image: nerozane/lmpclstr-node:1.1
    hostname: node03
    container_name: lmpnode03
    <<: *lmpenv
    networks:
      - guriang
    volumes:
      - gshare:/home/share
      - ./slurm.conf:/usr/local/etc/slurm.conf

  node04:
    image: nerozane/lmpclstr-node:1.1
    hostname: node04
    container_name: lmpnode04
    <<: *lmpenv
    networks:
      - guriang
    volumes:
      - gshare:/home/share
      - ./slurm.conf:/usr/local/etc/slurm.conf

volumes:
  gshare:
  slurmstate:

networks:
  guriang:
